import { component$, useComputed$ } from "@builder.io/qwik";
import { ORDER_RECEIPT_DIALOG_ID } from "~/constants/enum";
import { Dialog, DialogBody } from ".";
import type { DialogProps } from "../../../types";
import type { OrderFormType } from "~/validation/orderSchema";
import { calcOrderTotal } from "~/utils/order";

interface Props extends DialogProps {
  order: OrderFormType | undefined;
}

export const ReceiptDialog = component$<Props>(({ show, order, hide }) => {
  const total = useComputed$(() => {
    if (!order) return 0;
    return calcOrderTotal(order);
  });
  return (
    <Dialog
      id={ORDER_RECEIPT_DIALOG_ID}
      show={show.value}
      hide={hide}
      title="Receipt"
      closeOnOutsideClick={false}
    >
      <DialogBody>
        <div class="print">
          <div class="text-center">
            <h1 class="text-2xl font-bold">Sales Tax Invoice</h1>
            <p>Rruga Ali Demi, Tirane</p>
          </div>
          <div class="border-b-2 border-dashed  py-2">
            <div class="flex justify-between">
              <p>TIN</p>
              <p>123456789</p>
            </div>
            <div class="flex justify-between">
              <p>Date/Time</p>
              <p>{order?.date}</p>
            </div>
            <div class="flex justify-between">
              <p>Receipt No.</p>
              <p>{order?.docNo}</p>
            </div>
            <div class="flex justify-between">
              <p>Customer Name</p>
              <p>{order?.customer.name}</p>
            </div>
            <div class="flex justify-between">
              <p>Business Unit</p>
              <p>Fashion</p>
            </div>
            <div class="flex justify-between">
              <p>Payment Method</p>
              <p>{order?.payment.method}</p>
            </div>
          </div>

          <div>
            {order?.items.map((item, i) => {
              return (
                <div key={i} class="border-b-2 border-dashed">
                  <div>{item.name}</div>
                  <div class="flex justify-between">
                    <div>
                      {item.quantity} {item.unit} x {item.unitPrice}
                    </div>
                    <div>111111 Lek</div>
                  </div>
                </div>
              );
            })}
          </div>

          <div class="border-b-2 border-dashed  py-2">
            <div class="flex justify-between">
              <h2 class="text-xl font-bold">Total</h2>
              <div>
                {total.value} {order?.currency}
              </div>
            </div>
            <div class="flex justify-between">
              <h2>Payment amount</h2>
              <div>ssssss currency</div>
            </div>
          </div>

          <div class="border-b-2 border-dashed  py-2">
            <div class="flex justify-between">
              <p>No Tax itemsTaxPercentagetoFixed%</p>
              <div>itemsTotalNoTax Lek</div>
            </div>
            <div class="flex justify-between">
              <h2>Tax (itemsTaxPercentagetoFixed%)</h2>
              <div>itemsTaxAmount Lek</div>
            </div>
          </div>

          <div>
            <div>
              {/* <Image
              src="https://firebasestorage.googleapis.com/v0/b/my-pos-9f542.appspot.com/o/QR_code_for_mobile_English_Wikipedia.svg?alt=media&token=a6984d84-cfee-42e2-881b-788542548f49"
              width={200}
              height={200}
              alt="QR Code"
              class="mx-auto"
            /> */}
            </div>

            <div class="text-center">
              Generated by: <span>Qwik-Pos</span>
            </div>
          </div>
        </div>
      </DialogBody>
    </Dialog>
  );
});
